### ISSUE TITLE
Paytm | Github Repository Removal Request - https://github.com/CDorothy/Ajio_payment_automation

### ISSUE THREAD

**Issue by Cybersecurity-Specialist** [CDorothy/Ajio_payment_automation#1]
Greetings,

My name is Lou Dia, a Security Analyst who works on behalf of our client Paytm.

Our client noticed the following repository and has reported to us that they do not authorize nor have an affiliation with you to use their brand name.

Repository URL in question: https://github.com/CDorothy/Ajio_payment_automation

Our client has confirmed that this repository is not authorized to use their brand and be associated with this project. 

We ask that you delete or remove anything related to our client on this repository as this is not authorized and violates the trademark rights of Paytm. To avoid any legal action, please remove it immediately.

Your cooperation is highly appreciated.

Respectfully yours, 
Lou Dia
Cybersecurity Analyst

**Comment by CDorothy** [comment]
Removed the Paytm name instances from the repository.
